AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ECM as Lambda.

Resources:
  DOCSTORENodeJSLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs12.x
      ContentUri: dist
      Description: nodejs layer for docstore
      LayerName: DocStoreLayer

Outputs:
  DOCSTORELayer:
    Description: layer arn
    Value: !Ref DOCSTORENodeJSLayer
    Export:
      Name: !Sub "${AWS::StackName}-DocStoreLayer"
