AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ECM as Lambda.

Parameters:
  FoundationStackName:
    Description: Name of the stack that contains common and shared resources
    Type: String
Resources:
  ECMNestJSFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambda-entry-point.handler
      Runtime: nodejs12.x
      CodeUri: dist/app-lambda.zip
      MemorySize: 1512
      Timeout: 60
      Environment:
        Variables:
          DOCUMENTS_TABLE_NAME: documents-store-dev
          BUCKET_NAME: documents-store-181929501415-dev
          USE_DISCOVERED_ID: true
      Layers:
        - Fn::ImportValue:
            !Sub ${FoundationStackName}-DocStoreLayer
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Policies:
        - Statement:
            - Effect: "Allow"
              Action:
                - 'lambda:GetLayerVersion'
              Resource:
                - 'arn:aws:lambda:*:*:layer:*:*'
            - Effect: "Allow"
              Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource:
                - '*'
            - Effect: "Allow"
              Action:
                - 's3:*Object'
                - 's3:ListBucket'
                - 's3:*'
              Resource:
                - 'arn:aws:s3:::documents-store-181929501415-dev/*'
            - Effect: "Allow"
              Action:
                - 'dynamodb:*'
              Resource:
                - 'arn:aws:dynamodb:*:*:table/documents-store-dev'
Outputs:
  LambdaECMNestApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/documents'
    Export:
      Name: DocStoreApi
