AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ECM as Lambda.

Parameters:
  FoundationStackName:
    Description: Name of the stack that contains common and shared resources
    Type: String
Resources:
  ECMNestJSFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambda-entry-point.handler
      Runtime: nodejs12.x
      CodeUri: deploy/nest-lambda.zip
      MemorySize: 1512
      Timeout: 60
      Layers:
        Value:
          Fn::ImportValue: !Sub ${FoundationStackName}-DOCSTORELayer
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Policies:
        - Statement:
            - Effect: "Allow"
              Action:
                - 'lambda:GetLayerVersion'
              Resource:
                - 'arn:aws:lambda:*:*:layer:*:*'
            - Effect: "Allow"
              Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource:
                - '*'
Outputs:
  LambdaECMNestApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/documents'
    Export:
      Name: LambdaNestApi
